# Generated by Django 2.2.5 on 2019-09-22 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='user name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('avatar', models.ImageField(default='def_face.jpg', upload_to='images', verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
