# Generated by Django 2.2.5 on 2019-09-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Заголовок: ')),
                ('body', models.TextField(verbose_name='Содержание: ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано: ')),
                ('tags', models.CharField(max_length=50, verbose_name='Теги')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор: ')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='Ответ:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
                ('accept', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryanswer.Question')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ('-created',),
            },
        ),
    ]
