# Generated by Django 2.2.5 on 2019-09-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queryanswer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Question',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='Ответ:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано:')),
                ('accept', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryanswer.Question')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
