# Generated by Django 2.2.5 on 2019-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryanswer', '0003_vote_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='k', max_length=150),
            preserve_default=False,
        ),
    ]
